
1. Import numpy as np and print the version number

In [2]:
import numpy as np
np.__version__

'1.16.2'

### 2. Create a 1D array of numbers from 0 to 9


In [14]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. Create a 3×3 numpy array of all True’s(1's)


In [9]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Convert a 1D array to a 2D array with 2 rows


In [10]:
arr3 = np.arange(6).reshape(3,2)
arr3

array([[0, 1],
       [2, 3],
       [4, 5]])

#### 5. Write a NumPy program to generate six random integers between 10 and 30

In [11]:
a1 = np.random.randint(10,30,6)
a1

array([11, 26, 10, 23, 28, 17])

#### 6. Write a NumPy program to create a 3x3x3 array with random values


In [12]:
a2 = np.random.random((3,3,3))
a2

array([[[0.49158845, 0.98014399, 0.58414593],
        [0.76156911, 0.02355055, 0.43499158],
        [0.43170263, 0.88406895, 0.85388711]],

       [[0.8597193 , 0.1911712 , 0.75799484],
        [0.26922539, 0.99775286, 0.99844233],
        [0.72568679, 0.64996291, 0.05502102]],

       [[0.21331777, 0.31503993, 0.36858116],
        [0.70237441, 0.92019561, 0.52611093],
        [0.03117774, 0.60706488, 0.46335963]]])

#### 7.Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.


In [11]:
x = np.random.random((5,2))
print(x) 
x.min(), x.max()


[[0.61036299 0.12230683]
 [0.31495742 0.89260067]
 [0.11984505 0.18649001]
 [0.66013934 0.12086697]
 [0.76400648 0.83338486]]


(0.11984505479860752, 0.8926006680630544)

#### 8 Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable


In [13]:
import numpy as np
n = np.random.rand(10, 4)
print(n)
y= n[:5, :]
print(y)

[[0.69000635 0.47355101 0.4761114  0.75693755]
 [0.69407347 0.19291352 0.04267955 0.35101113]
 [0.70340797 0.65865762 0.46600884 0.92166111]
 [0.61981583 0.10204185 0.7631809  0.60885525]
 [0.2386988  0.96992819 0.06443865 0.40088808]
 [0.44828068 0.5302005  0.61652277 0.45574421]
 [0.02455206 0.93609236 0.01819664 0.40262595]
 [0.66918756 0.34245122 0.9883006  0.04728296]
 [0.10299066 0.13670077 0.03683546 0.32244175]
 [0.81682469 0.31600931 0.8674786  0.96512284]]
[[0.69000635 0.47355101 0.4761114  0.75693755]
 [0.69407347 0.19291352 0.04267955 0.35101113]
 [0.70340797 0.65865762 0.46600884 0.92166111]
 [0.61981583 0.10204185 0.7631809  0.60885525]
 [0.2386988  0.96992819 0.06443865 0.40088808]]


### 9.How to reverse the rows of a 2D array?

In [20]:
arr=[[1,2],[3,4],[5,6]] 
print(arr[::-1])

[[5, 6], [3, 4], [1, 2]]


### 10. Create 1D array with random numbers and replace all odd numbers in arr with -1


In [64]:
a3 =  np.random.randint(1,7,10)
num = 0
print(a3)
for i in range(len(a3)):#10 0-9
    if a3[i] % 2 != 0:
        a3[i]=-1
a3

    

[3 4 4 5 1 6 2 3 5 2]


array([-1,  4,  4, -1, -1,  6,  2, -1, -1,  2])